services:
  - type: web
    name: droply
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true    services:
      - type: web
        name: droply
        env: node
        buildCommand: pnpm install && pnpm build
        startCommand: pnpm start
        autoDeploy: true
        envVars:
          - key: NODE_ENV
            value: production